ktor:
  development: true
  application:
    modules:
      - nesski.de.ApplicationKt.module
  deployment:
    port: 8484
    watch:
      - classes
    host: wahoo.calendar
oauth:
  clientId: ""
  clientSecret: ""
