version: '3'

services:
  nginx:
    image: blacklabelops/nginx
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    networks:
      - wahoonet
    environment:
      - SERVER1SERVER_NAME=wahoo.nesski.com
      - SERVER1REVERSE_PROXY_LOCATION1=/
      - SERVER1REVERSE_PROXY_PASS1=http://host.docker.internal:8484
      - SERVER1HTTPS_ENABLED=true
      - SERVER1CERTIFICATE_FILE=/etc/ssl/private/wahoo/wahoo.nesski.com.crt
      - SERVER1CERTIFICATE_KEY=/etc/ssl/private/wahoo/wahoo.nesski.com.key
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - data:/home/nginx
      - www:/var/lib/nginx/html
      - data:/var/log/nginx
      - ./certs:/etc/ssl/private

volumes:
  data:
  www:

networks:
  wahoonet:
