package nesski.de.ics

import nesski.de.models.UserPlanItem
import net.fortuna.ical4j.data.CalendarOutputter
import net.fortuna.ical4j.model.Calendar
import net.fortuna.ical4j.model.component.VEvent
import net.fortuna.ical4j.model.property.CalScale
import net.fortuna.ical4j.model.property.Description
import net.fortuna.ical4j.model.property.ProdId
import net.fortuna.ical4j.model.property.Status
import net.fortuna.ical4j.model.property.Transp
import net.fortuna.ical4j.model.property.Uid
import net.fortuna.ical4j.model.property.Version
import net.fortuna.ical4j.model.ParameterList
import org.slf4j.LoggerFactory
import java.io.StringWriter
import java.time.LocalDate

private val log = LoggerFactory.getLogger("IcsBuilder")

/**
 * Result of building an ICS calendar from workout plan items.
 *
 * @property icsContent The full VCALENDAR string (RFC 5545 compliant, generated by ical4j)
 * @property exportedCount Number of workouts successfully converted to VEVENTs
 * @property skippedCount Number of workouts skipped due to bad/missing data
 * @property skippedReasons Details about why specific workouts were skipped
 */
data class IcsBuildResult(
    val icsContent: String,
    val exportedCount: Int,
    val skippedCount: Int,
    val skippedReasons: List<String> = emptyList()
)

/**
 * Builds RFC 5545-compliant VCALENDAR content with VEVENT entries from
 * Wahoo SYSTM training plan items using ical4j.
 *
 * Each workout becomes an all-day calendar event (DATE-only DTSTART/DTEND)
 * that is universally compatible with Apple Calendar, Google Calendar,
 * Yahoo Calendar, and Outlook.
 *
 * Key VEVENT decisions:
 * - DTSTART/DTEND use DATE-only format for all-day placeholder events
 * - Users drag the event to their preferred time slot
 * - Duration is communicated in SUMMARY text (e.g. "Workout (30 min)")
 * - TRANSP:TRANSPARENT so the event doesn't block the whole day
 * - STATUS:CONFIRMED for a clean calendar display
 * - UID uses agendaId (falling back to workoutId or generated value) + @wahoo suffix
 */
object IcsBuilder {

    private const val PRODID = "-//WahooCLI//SYSTM Plan Export//EN"

    /**
     * Build a complete VCALENDAR string from a list of [UserPlanItem]s.
     *
     * Workouts with missing plannedDate are skipped. Rest days (type == "Rest")
     * are skipped. Items with no prospect (no workout details) are skipped.
     *
     * @param items The workout plan items from the GraphQL API
     * @return An [IcsBuildResult] with the ICS content and export statistics
     */
    fun build(items: List<UserPlanItem>): IcsBuildResult {
        val events = mutableListOf<VEvent>()
        val skippedReasons = mutableListOf<String>()
        var skippedCount = 0

        for (item in items) {
            // Skip rest days
            if (item.type?.equals("Rest", ignoreCase = true) == true) {
                log.debug("Skipping rest day: agendaId=${item.agendaId}")
                skippedCount++
                skippedReasons.add("Rest day skipped: agendaId=${item.agendaId ?: "unknown"}")
                continue
            }

            // Skip items with no planned date
            if (item.plannedDate.isNullOrBlank()) {
                log.warn("Skipping item with no planned date: agendaId=${item.agendaId}")
                skippedCount++
                skippedReasons.add("No planned date: agendaId=${item.agendaId ?: "unknown"}")
                continue
            }

            // Parse the date from ISO-8601 datetime
            val eventDate = try {
                LocalDate.parse(item.plannedDate.substringBefore("T"))
            } catch (e: Exception) {
                log.warn("Skipping item with unparseable date '${item.plannedDate}': ${e.message}")
                skippedCount++
                skippedReasons.add("Unparseable date '${item.plannedDate}': agendaId=${item.agendaId ?: "unknown"}")
                continue
            }

            val prospect = item.prospects?.firstOrNull()

            // Skip items with no workout details (no prospect and no type)
            if (prospect == null && item.type.isNullOrBlank()) {
                log.warn("Skipping item with no workout details: agendaId=${item.agendaId}")
                skippedCount++
                skippedReasons.add("No workout details: agendaId=${item.agendaId ?: "unknown"}")
                continue
            }

            val event = buildVEvent(item, prospect, eventDate)
            events.add(event)
        }

        val icsContent = buildCalendar(events)

        log.info("ICS build complete: ${events.size} exported, $skippedCount skipped")

        return IcsBuildResult(
            icsContent = icsContent,
            exportedCount = events.size,
            skippedCount = skippedCount,
            skippedReasons = skippedReasons
        )
    }

    /**
     * Build a single VEVENT component for one workout.
     *
     * Creates an all-day event (DATE-only) so the user can drag it
     * to their preferred time in any calendar app.
     */
    internal fun buildVEvent(
        item: UserPlanItem,
        prospect: nesski.de.models.Prospect?,
        eventDate: LocalDate
    ): VEvent {
        val summary = formatSummary(item, prospect)

        // All-day event: DTSTART = date, DTEND = date + 1
        val event = VEvent(eventDate, eventDate.plusDays(1), summary)

        // UID with @wahoo suffix for stable identification
        event.add<VEvent>(Uid(resolveUid(item, prospect)))

        // STATUS:CONFIRMED — clean calendar display
        event.add<VEvent>(Status(Status.VALUE_CONFIRMED))

        // TRANSP:TRANSPARENT — doesn't block the whole day
        event.add<VEvent>(Transp(Transp.VALUE_TRANSPARENT))

        // DESCRIPTION with workout details and drag instruction
        val description = formatDescription(item, prospect)
        if (description.isNotBlank()) {
            event.add<VEvent>(Description(description))
        }

        return event
    }

    /**
     * Wrap VEVENT entries in a VCALENDAR envelope using ical4j,
     * then serialize to a compliant string via CalendarOutputter.
     */
    private fun buildCalendar(events: List<VEvent>): String {
        val calendar = Calendar()
        calendar.add<Calendar>(ProdId(PRODID))
        calendar.add<Calendar>(Version(ParameterList(), Version.VALUE_2_0))
        calendar.add<Calendar>(CalScale(CalScale.VALUE_GREGORIAN))

        for (event in events) {
            calendar.add<Calendar>(event)
        }

        val writer = StringWriter()
        val outputter = CalendarOutputter(false) // false = don't validate (we control structure)
        outputter.output(calendar, writer)
        return writer.toString().trimEnd()
    }

    /**
     * Resolve a unique ID for the VEVENT.
     * Priority: agendaId > prospect.workoutId > generated fallback.
     * All UIDs get @wahoo suffix for domain uniqueness.
     */
    private fun resolveUid(item: UserPlanItem, prospect: nesski.de.models.Prospect?): String {
        val baseUid = item.agendaId
            ?: prospect?.workoutId
            ?: "wahoo-${item.plannedDate?.replace(Regex("[^0-9]"), "") ?: System.currentTimeMillis()}"
        return "$baseUid@wahoo"
    }

    /**
     * Format the SUMMARY field with sport emoji, workout name, and duration hint.
     *
     * Format: "emoji WorkoutName (Xmin)" — duration helps users know how long
     * the workout will take when they schedule it.
     */
    internal fun formatSummary(item: UserPlanItem, prospect: nesski.de.models.Prospect?): String {
        val workoutName = prospect?.name ?: item.type ?: "Workout"
        val sportType = prospect?.type ?: prospect?.style ?: item.type
        val emoji = SportEmoji.forType(sportType)

        val duration = prospect?.plannedDuration
        val durationHint = if (duration != null) {
            val totalMinutes = (duration * 60).toInt()
            " (${totalMinutes} min)"
        } else {
            ""
        }

        return "$emoji $workoutName$durationHint"
    }

    /**
     * Format the DESCRIPTION field with workout type, plan info, and drag instruction.
     */
    private fun formatDescription(item: UserPlanItem, prospect: nesski.de.models.Prospect?): String {
        val parts = mutableListOf<String>()

        val workoutType = prospect?.type ?: prospect?.style ?: item.type
        if (!workoutType.isNullOrBlank()) {
            parts.add("Type: $workoutType")
        }

        if (item.plan?.name != null) {
            parts.add("Plan: ${item.plan.name.trim()}")
        }

        val duration = prospect?.plannedDuration
        if (duration != null) {
            val totalMinutes = (duration * 60).toInt()
            parts.add("Duration: ${totalMinutes} min")
        }

        parts.add("Drag this event to a time that works for you.")

        return parts.joinToString("\n")
    }
}
